export const Icons = {
  user: require('../assets/Icons/user.png'),
  login: require('../assets/Icons/login.png'),
  email: require('../assets/Icons/email.png'),
  lock: require('../assets/Icons/lock.png'),
  add_user: require('../assets/Icons/add_user.png'),
  cross: require('../assets/Icons/cross.png'),
  view: require('../assets/Icons/view.png'),
  hide: require('../assets/Icons/hide.png'),
  home: require('../assets/Icons/home.png'),
  settings: require('../assets/Icons/settings.png'),
  audits: require('../assets/Icons/audits.png'),
  edit: require('../assets/Icons/edit.png'),
  account: require('../assets/Icons/account.png'),
  help: require('../assets/Icons/help.png'),
  logout: require('../assets/Icons/logout.png'),
  delete: require('../assets/Icons/delete.png'),
  delete_user: require('../assets/Icons/delete_user.png'),
  notification: require('../assets/Icons/notification.png'),
  close: require('../assets/Icons/close.png'),
  ic_notification: require('../assets/Icons/ic_notification.png'),
  ic_search: require('../assets/Icons/ic_search.png'),
  ic_back: require('../assets/Icons/ic_back.png'),
  ic_add: require('../assets/Icons/ic_add.png'),
  calendar: require('../assets/Icons/calendar.png'),
  ic_map: require('../assets/Icons/ic_map.png'),
  ic_download: require('../assets/Icons/ic_download.png'),
  ic_list: require('../assets/Icons/ic_list.png'),
  ic_refresh: require('../assets/Icons/ic_refresh.png'),
  map1: require('../assets/Icons/map1.png'),
  map2: require('../assets/Icons/map2.png'),
  plus: require('../assets/Icons/plus.png'),
  filter: require('../assets/Icons/filter.png'),
  ic_phone: require('../assets/Icons/ic_phone.png'),
  ic_qr: require('../assets/Icons/ic_qr.png'),
  ic_edit: require('../assets/Icons/ic_edit.png'),
  camera: require('../assets/Icons/camera.png'),
  gallery: require('../assets/Icons/gallery.png'),
  theme: require('../assets/Icons/theme.png'),
  ic_share: require('../assets/Icons/ic_share.png'),
  tick: require('../assets/Icons/tick.png'),
};

export const GIF = {
  download:
    'https://s3-alpha-sig.figma.com/img/b86a/aca3/a2940d17df5401f00eef43bc8914b965?Expires=1734912000&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=U1waHIRVwn8-ymi-u8J0Wit5CVay7SgHiel-bY1bByXPauqWm-smjGYPszsQDC~ia6w~QcobgZ6PUYMvSDmEfQWGy87-VCM-yKj~hGrE7SdjCcmxASYiC0oTb0MfbtGS7C0sDhy3G1TCQZh1~tRoVpOaBZqGnN~LLeYGY3TNW2yRGwbZmxJV1Msd4yxA7cfOZSNo7PquRxcM8xZSeIrq4F-p~xSGIIf80OvVGg7BizE0KS-AIoMgjpSFxRykVszFaWHYVCYPeDdoDSYcMAgUYtDOHBq0VLpao3F~HHJdaBSTMpgRNEV0avOouQ~YKijPgqzfMQf5mmHTVNGPSKH3jw__',
};
