export const IS_LOADING = 'IS_LOADING';

export const SET_APP_THEME = 'SET_APP_THEME';

export const SET_APP_LANGUAGE_LIST = 'SET_APP_LANGUAGE_LIST';

export const SET_USER_APP_LANGUAGE = 'SET_USER_APP_LANGUAGE';

export const SET_FONT_VALUE = 'SET_FONT_VALUE';

export const SET_USER_INFO = 'SET_USER_INFO';

export const SET_GROUP_LIST = 'SET_GROUP_LIST';

export const GET_AUDITS = 'GET_AUDITS';
export const GET_AUDITS_DETAILS = 'GET_AUDITS_DETAILS';
